### ISSUE TITLE
Duplicated `tail_ontologies` fails in `create_tree_visualisation`

### ISSUE THREAD

**Issue by jdreo** [biocypher/biocypher#273]
When tailing-in the same ontology several times, the tree visualisation stalls.

# Detailed description

I want to tail-in the Sequence Ontology (SO) at two different location within Biolink.
The SO has several classes right under `Thing`, which I want to use:
```
biocypher:
    head_ontology:
        url: https://github.com/biolink/biolink-model/raw/v3.2.1/biolink-model.owl.ttl
        root_node: entity

    tail_ontologies:
        so_variant:
            url: http://purl.obolibrary.org/obo/so.owl
            head_join_node: sequence variant
            tail_join_node: sequence_variant
        so_feature:
            url: http://purl.obolibrary.org/obo/so.owl
            head_join_node: attribute
            tail_join_node: sequence_feature
```

When running this config, however, the `bc.summary()` call stalls, and show the following stack when interrupted:

> ^CTraceback (most recent call last):
>   File "/home/jdreo/code/oncodashkb/./weave.py", line 71, in <module>
>     bc.summary()
>   File "/home/jdreo/code/biocypher/biocypher/_core.py", line 652, in summary
>     self.show_ontology_structure()
>   File "/home/jdreo/code/biocypher/biocypher/_core.py", line 543, in show_ontology_structure
>     return self._ontology.show_ontology_structure(**kwargs)
>   File "/home/jdreo/code/biocypher/biocypher/_ontology.py", line 558, in show_ontology_structure
>     tree = _misc.create_tree_visualisation(G)
>   File "/home/jdreo/code/biocypher/biocypher/_misc.py", line 125, in create_tree_visualisation
>     [various line of code in the same function]
> KeyboardInterrupt

# Configuration

- biocypher: v0.5.23
- OS: Ubuntu 22.04.3 LTS
