### ISSUE TITLE
Ontology: Make reverse_labels configurable via biocypher_config.yaml

### ISSUE THREAD

**Issue by nilskre** [biocypher/biocypher#313]
Do I understand the code correctly, that at the moment it is not possible to define in the `biocypher_config.yaml`, whether the node id and label should be switched (it is default to `true`).

It would be convenient to have the possibility to optionally define it in the `biocypher_config.yaml` and then pass on the defined value. 
```
  head_ontology:
    url: config/ontologies/custom.ttl
    root_node: Ontology
    switch_label_and_id: <true, false>
```

If this is desired functionality, I will create a PR for this.
