### ISSUE TITLE
[BUG]: Default bin prefix in neo4j writer

### ISSUE THREAD

**Issue by ecarrenolozano** [biocypher/biocypher#442]
### Source

poetry

### Python version

3.12

### BioCypher version

biocypher v0.9.3

### OS platform and distribution

Linux Ubuntu 22.04 64-bit

## Issue:
- Once a `neo4j-admin-import-call-sh` has been generated. Only the `version` section is ignoring the parameter defined in the `biocypher_config.yaml` file.

## Input

`biocypher_config.yaml` file:
```yaml
neo4j:
  delimiter: '\t'
  array_delimiter: "|"
  skip_duplicate_nodes: true
  skip_bad_relationships: true
  import_call_bin_prefix: /opt/neo4j-path/  # path to "neo4j-admin"
```

## Output

![Image](https://github.com/user-attachments/assets/43ccc4a3-06a4-42cc-9081-d436bd182512)

### Relevant LOG output

```shell

```

### Code of Conduct

- [x] I agree to follow this project's Code of Conduct
